-- MySQL Script generated by MySQL Workbench
-- Thu May 16 18:00:58 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `loja` ;

-- -----------------------------------------------------
-- Schema loja
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `loja` DEFAULT CHARACTER SET utf8 ;
USE `loja` ;

-- -----------------------------------------------------
-- Table `loja`.`aluguel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`aluguel` ;

CREATE TABLE IF NOT EXISTS `loja`.`aluguel` (
  `id_aluguel` INT NOT NULL AUTO_INCREMENT,
  `dt_aluguel` DATETIME NOT NULL,
  `dt_devolucao` DATETIME NOT NULL,
  `status` TINYINT NOT NULL DEFAULT 0,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_aluguel`),
  INDEX `fk_aluguel_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_aluguel_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `loja`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`aluguel_has_filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`aluguel_has_filme` ;

CREATE TABLE IF NOT EXISTS `loja`.`aluguel_has_filme` (
  `id_aluguel` INT NOT NULL,
  `id_filme` INT NOT NULL,
  PRIMARY KEY (`id_aluguel`, `id_filme`),
  INDEX `fk_aluguel_has_filme_filme1_idx` (`id_filme` ASC) VISIBLE,
  INDEX `fk_aluguel_has_filme_aluguel1_idx` (`id_aluguel` ASC) VISIBLE,
  CONSTRAINT `fk_aluguel_has_filme_aluguel1`
    FOREIGN KEY (`id_aluguel`)
    REFERENCES `loja`.`aluguel` (`id_aluguel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluguel_has_filme_filme1`
    FOREIGN KEY (`id_filme`)
    REFERENCES `loja`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`ator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`ator` ;

CREATE TABLE IF NOT EXISTS `loja`.`ator` (
  `id_ator` INT NOT NULL AUTO_INCREMENT,
  `nome_ator` VARCHAR(100) NOT NULL,
  `nome_real` VARCHAR(100) NULL,
  `dt_nasc` DATE NULL,
  PRIMARY KEY (`id_ator`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`categoria` ;

CREATE TABLE IF NOT EXISTS `loja`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`cliente` ;

CREATE TABLE IF NOT EXISTS `loja`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` INT NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`endereco` ;

CREATE TABLE IF NOT EXISTS `loja`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `bairro` VARCHAR(100) NULL,
  `rua` VARCHAR(100) NULL,
  `numero` INT NULL,
  `complemento` VARCHAR(255) NULL,
  `cidade` VARCHAR(100) NULL,
  `id_cliente` INT NOT NULL,
  PRIMARY KEY (`id_endereco`),
  INDEX `fk_endereco_cliente1_idx` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_endereco_cliente1`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `loja`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`filme`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`filme` ;

CREATE TABLE IF NOT EXISTS `loja`.`filme` (
  `id_filme` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_filme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`filme_has_ator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`filme_has_ator` ;

CREATE TABLE IF NOT EXISTS `loja`.`filme_has_ator` (
  `id_filme` INT NOT NULL,
  `id_ator` INT NOT NULL,
  PRIMARY KEY (`id_filme`, `id_ator`),
  INDEX `fk_filme_has_ator_ator1_idx` (`id_ator` ASC) VISIBLE,
  INDEX `fk_filme_has_ator_filme1_idx` (`id_filme` ASC) VISIBLE,
  CONSTRAINT `fk_filme_has_ator_filme1`
    FOREIGN KEY (`id_filme`)
    REFERENCES `loja`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_ator_ator1`
    FOREIGN KEY (`id_ator`)
    REFERENCES `loja`.`ator` (`id_ator`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`filme_has_categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`filme_has_categoria` ;

CREATE TABLE IF NOT EXISTS `loja`.`filme_has_categoria` (
  `id_filme` INT NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_filme`, `id_categoria`),
  INDEX `fk_filme_has_categoria_categoria1_idx` (`id_categoria` ASC) VISIBLE,
  INDEX `fk_filme_has_categoria_filme1_idx` (`id_filme` ASC) VISIBLE,
  CONSTRAINT `fk_filme_has_categoria_filme1`
    FOREIGN KEY (`id_filme`)
    REFERENCES `loja`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_filme_has_categoria_categoria1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `loja`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `loja`.`fita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `loja`.`fita` ;

CREATE TABLE IF NOT EXISTS `loja`.`fita` (
  `id_Fita` INT NOT NULL AUTO_INCREMENT,
  `id_filme` INT NOT NULL,
  PRIMARY KEY (`id_Fita`),
  INDEX `fk_fita_filme_idx` (`id_filme` ASC) VISIBLE,
  CONSTRAINT `fk_fita_filme`
    FOREIGN KEY (`id_filme`)
    REFERENCES `loja`.`filme` (`id_filme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
