-- MySQL Script generated by MySQL Workbench
-- Mon May 20 16:40:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema UnBCineFlix
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `UnBCineFlix` ;

-- -----------------------------------------------------
-- Schema UnBCineFlix
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UnBCineFlix` DEFAULT CHARACTER SET utf8 ;
USE `UnBCineFlix` ;

-- -----------------------------------------------------
-- Table `UnBCineFlix`.`chair`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnBCineFlix`.`chair` ;

CREATE TABLE IF NOT EXISTS `UnBCineFlix`.`chair` (
  `idchair` INT NOT NULL AUTO_INCREMENT,
  `row` INT UNSIGNED NOT NULL,
  `column` INT UNSIGNED NOT NULL,
  `movieTheater_id` INT NOT NULL,
  PRIMARY KEY (`idchair`),
  INDEX `fk_chair_movieTheater_idx` (`movieTheater_id` ASC) VISIBLE,
  CONSTRAINT `fk_chair_movieTheater`
    FOREIGN KEY (`movieTheater_id`)
    REFERENCES `UnBCineFlix`.`movieTheater` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UnBCineFlix`.`movieTheater`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `UnBCineFlix`.`movieTheater` ;

CREATE TABLE IF NOT EXISTS `UnBCineFlix`.`movieTheater` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `number` VARCHAR(45) NOT NULL,
  `Name` VARCHAR(100) NULL,
  `MaxRow` INT UNSIGNED NOT NULL,
  `maxColumn` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
